<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    public function run()
    {
        // $menus = [
        //     ['id' => 1, 'image_id' => null, 'name' => 'primary', 'class' => null, 'status' => '{"fr":"1","en":"1","nl":"1"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 2, 'image_id' => null, 'name' => 'footer', 'class' => null, 'status' => '{"fr":"1","en":"1","nl":"1"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 3, 'image_id' => null, 'name' => 'social', 'class' => null, 'status' => '{"fr":"1","en":"1","nl":"1"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 4, 'image_id' => null, 'name' => 'legal', 'class' => null, 'status' => '{"fr": 1, "en": 1, "nl": 1}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        // ];
        // $menulinks = [
        //     ['id' => 1, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => null, 'image_id' => null, 'position' => 1, 'target' => null, 'class' => null, 'status' => '{"en": 1, "fr": 1, "nl": 1}', 'description' => '{"en": null, "fr": null, "nl": null}', 'title' => '{"en": "Home", "fr": "Accueil", "nl": "Home"}', 'url' => '{"en": null, "fr": null, "nl": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 2, 'menu_id' => 1, 'page_id' => 2, 'parent_id' => null, 'image_id' => null, 'position' => 2, 'target' => null, 'class' => null, 'status' => '{"en": 1, "fr": 1, "nl": 1}', 'description' => '{"en": null, "fr": null, "nl": null}', 'title' => '{"en": "Contact", "fr": "Contact", "nl": "Contact"}', 'url' => '{"en": null, "fr": null, "nl": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 3, 'menu_id' => 2, 'page_id' => 2, 'parent_id' => null, 'image_id' => null, 'position' => 1, 'target' => null, 'class' => null, 'status' => '{"en": 1, "fr": 1, "nl": 1}', 'description' => '{"en": null, "fr": null, "nl": null}', 'title' => '{"en": "Contact", "fr": "Contact", "nl": "Contact"}', 'url' => '{"en": null, "fr": null, "nl": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 4, 'menu_id' => 3, 'page_id' => null, 'parent_id' => null, 'image_id' => null, 'position' => 1, 'target' => '_blank', 'class' => 'btn-facebook', 'status' => '{"en": 1, "fr": 1, "nl": 1}', 'description' => '{"en": null, "fr": null, "nl": null}', 'title' => '{"en": "Facebook", "fr": "Facebook", "nl": "Facebook"}', 'url' => '{"en": "https://www.facebook.com", "fr": "https://www.facebook.com", "nl": "https://www.facebook.com"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 5, 'menu_id' => 3, 'page_id' => null, 'parent_id' => null, 'image_id' => null, 'position' => 2, 'target' => '_blank', 'class' => 'btn-linkedin', 'status' => '{"en": 1, "fr": 1, "nl": 1}', 'description' => '{"en": null, "fr": null, "nl": null}', 'title' => '{"en": "LinkedIn", "fr": "LinkedIn", "nl": "LinkedIn"}', 'url' => '{"en": "https://www.linkedin.com", "fr": "https://www.linkedin.com", "nl": "https://www.linkedin.com"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 6, 'menu_id' => 3, 'page_id' => null, 'parent_id' => null, 'image_id' => null, 'position' => 3, 'target' => '_blank', 'class' => 'btn-twitter', 'status' => '{"en": 1, "fr": 1, "nl": 1}', 'description' => '{"en": null, "fr": null, "nl": null}', 'title' => '{"en": "Twitter", "fr": "Twitter", "nl": "Twitter"}', 'url' => '{"en": "https://twitter.com", "fr": "https://twitter.com", "nl": "https://twitter.com"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 7, 'menu_id' => 3, 'page_id' => null, 'parent_id' => null, 'image_id' => null, 'position' => 4, 'target' => '_blank', 'class' => 'btn-instagram', 'status' => '{"en": 1, "fr": 1, "nl": 1}', 'description' => '{"en": null, "fr": null, "nl": null}', 'title' => '{"en": "Instagram", "fr": "Instagram", "nl": "Instagram"}', 'url' => '{"en": "https://www.instagram.com", "fr": "https://www.instagram.com", "nl": "https://www.instagram.com"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 8, 'menu_id' => 3, 'page_id' => null, 'parent_id' => null, 'image_id' => null, 'position' => 5, 'target' => '_blank', 'class' => 'btn-youtube', 'status' => '{"en": 1, "fr": 1, "nl": 1}', 'description' => '{"en": null, "fr": null, "nl": null}', 'title' => '{"en": "YouTube", "fr": "YouTube", "nl": "YouTube"}', 'url' => '{"en": "https://www.youtube.com", "fr": "https://www.youtube.com", "nl": "https://www.youtube.com"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 9, 'menu_id' => 4, 'page_id' => 3, 'parent_id' => null, 'image_id' => null, 'position' => 0, 'target' => null, 'class' => null, 'status' => '{"en": 1, "fr": 1, "nl": 1}', 'description' => '{"en": null, "fr": null, "nl": null}', 'title' => '{"en": "Terms and conditions", "fr": "Conditions générales", "nl": "Algemene Voorwaarden"}', 'url' => '{"en": null, "fr": null, "nl": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 10, 'menu_id' => 4, 'page_id' => 4, 'parent_id' => null, 'image_id' => null, 'position' => 0, 'target' => null, 'class' => null, 'status' => '{"en": 1, "fr": 1, "nl": 1}', 'description' => '{"en": null, "fr": null, "nl": null}', 'title' => '{"en": "Privacy policy", "fr": "Charte vie privée", "nl": "Privacyverklaring"}', 'url' => '{"en": null, "fr": null, "nl": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        //     ['id' => 11, 'menu_id' => 4, 'page_id' => 5, 'parent_id' => null, 'image_id' => null, 'position' => 0, 'target' => null, 'class' => null, 'status' => '{"en": 1, "fr": 1, "nl": 1}', 'description' => '{"en": null, "fr": null, "nl": null}', 'title' => '{"en": "Cookie policy", "fr": "Politique des cookies", "nl": "Cookieverklaring"}', 'url' => '{"en": null, "fr": null, "nl": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

        //     // new sub menu 
           
        // ];
        $menus = [
            ['id' => 1, 'image_id' => null, 'name' => 'primary', 'class' => null, 'status' => '{"en":"1","hy":"1","ru":"1"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 2, 'image_id' => null, 'name' => 'footer', 'class' => null, 'status' => '{"en":"1","hy":"1","ru":"1"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 3, 'image_id' => null, 'name' => 'social', 'class' => null, 'status' => '{"en":"1","hy":"1","ru":"1"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 4, 'image_id' => null, 'name' => 'legal', 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ];
        // 4 - 9 = 3
        // 11 -14 = 10
        // 16 - 18 = 15 
        // 21 - 24 = 20 
        $menulinks = [
            ['id' => 1, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => null, 'image_id' => null, 'position' => 1, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "About Us", "hy": "Մեր Մասին", "ru": "О нас"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 2, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => null, 'image_id' => null, 'position' => 2, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Services", "hy": "Ծառայություններ", "ru": "Услуги:"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 3, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 2, 'image_id' => null, 'position' => 1, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Legal services", "hy": "Իրավաբանական ծառայություններ", "ru": "Юридические услуги:"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 4, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 3, 'image_id' => null, 'position' => 1, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Corporate law", "hy": "Կորպորատիվ իրավունք", "ru": "Корпоративное право"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 5, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 3, 'image_id' => null, 'position' => 2, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Transfer", "hy": "Տեղափոխում", "ru": "Передача"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 6, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 3, 'image_id' => null, 'position' => 3, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "IT Law and Startups", "hy": "ՏՏ իրավունք և ստարտափներ", "ru": "ИТ-право и стартапы"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 7, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 3, 'image_id' => null, 'position' => 4, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Citizenship and Residence", "hy": "Քաղաքացիություն և բնակություն", "ru": "Гражданство и место жительства"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 8, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 3, 'image_id' => null, 'position' => 5, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Capital markets", "hy": "Կապիտալի շուկաներ", "ru": "Рынки капитала"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 9, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 3, 'image_id' => null, 'position' => 6, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Contracts and Transactions", "hy": "Պայմանագրեր և գործարքներ", "ru": "Контракты и транзакции"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 10, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 2, 'image_id' => null, 'position' => 2, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Accounting services", "hy": "Հաշվապահական ծառայություններ", "ru": "Бухгалтерские услуги"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 11, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 10, 'image_id' => null, 'position' => 1, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Accounting", "hy": "Հաշվապահություն", "ru": "Бухгалтерский учет"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 12, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 10, 'image_id' => null, 'position' => 2, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Financial statement", "hy": "Ֆինանսական հաշվետվություն", "ru": "Финансовый отчет"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 13, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 10, 'image_id' => null, 'position' => 3, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Payroll services", "hy": "Աշխատավարձի ծառայություններ", "ru": "Зарплатные услуги"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 14, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 10, 'image_id' => null, 'position' => 4, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Audits", "hy": "Աուդիտներ", "ru": "Аудиты"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 15, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 2, 'image_id' => null, 'position' => 3, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Consulting services", "hy": "Խորհրդատվական ծառայություններ", "ru": "Консалтинговые услуги"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 16, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 15, 'image_id' => null, 'position' => 1, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Tax advice", "hy": "Հարկային խորհրդատվություն", "ru": "Налоговые консультации"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 17, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 15, 'image_id' => null, 'position' => 2, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Corporate consulting", "hy": "Կորպորատիվ խորհրդատվություն", "ru": "Корпоративный консалтинг"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 18, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 15, 'image_id' => null, 'position' => 3, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Business consulting", "hy": "Բիզնես խորհրդատվություն", "ru": "Бизнес-консалтинг"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 19, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => null, 'image_id' => null, 'position' => 3, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Tean", "hy": "Թիմ", "ru": "Команда"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 20, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => null, 'image_id' => null, 'position' => 4, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Resources", "hy": "Ռեսուրսներ", "ru": "Ресурсы"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 21, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 20, 'image_id' => null, 'position' => 1, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Blog", "hy": "Բլոգ", "ru": "Блог"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 22, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 20, 'image_id' => null, 'position' => 2, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "News", "hy": "Նորություններ", "ru": "Новости"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 23, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 20, 'image_id' => null, 'position' => 3, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Legal dictionary", "hy": "Իրավաբանական բառարան", "ru": "Юридический словарь"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 24, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => 20, 'image_id' => null, 'position' => 4, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Publications", "hy": "Հրապարակումներ", "ru": "Публикации"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 25, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => null, 'image_id' => null, 'position' => 5, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "News", "hy": "Նորություններ", "ru": "Партнеры"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 26, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => null, 'image_id' => null, 'position' => 6, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Partners", "hy": "Գործընկերներ", "ru": "Новости"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 27, 'menu_id' => 1, 'page_id' => 1, 'parent_id' => null, 'image_id' => null, 'position' => 7, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Contact", "hy": "Կոնտակտ", "ru": "Контакт"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           
           
            // ['id' => 2, 'menu_id' => 1, 'page_id' => 2, 'parent_id' => null, 'image_id' => null, 'position' => 2, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Contact", "hy": "Կապ", "ru": "Контакт"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            // ['id' => 28, 'menu_id' => 2, 'page_id' => 2, 'parent_id' => null, 'image_id' => null, 'position' => 1, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Contact", "hy": "Կապ", "ru": "Контакт"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            // ['id' => 29, 'menu_id' => 3, 'page_id' => null, 'parent_id' => null, 'image_id' => null, 'position' => 1, 'target' => '_blank', 'class' => 'btn-facebook', 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Facebook", "hy": "Ֆեյսբուք", "ru": "Фейсбук"}', 'url' => '{"en": "https://www.facebook.com", "hy": "https://www.facebook.com", "ru": "https://www.facebook.com"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            // ['id' => 30, 'menu_id' => 3, 'page_id' => null, 'parent_id' => null, 'image_id' => null, 'position' => 2, 'target' => '_blank', 'class' => 'btn-linkedin', 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "LinkedIn", "hy": "Լինքդին", "ru": "Линкедин"}', 'url' => '{"en": "https://www.linkedin.com", "hy": "https://www.linkedin.com", "ru": "https://www.linkedin.com"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            // ['id' => 31, 'menu_id' => 3, 'page_id' => null, 'parent_id' => null, 'image_id' => null, 'position' => 3, 'target' => '_blank', 'class' => 'btn-twitter', 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Twitter", "hy": "Թվիթեր", "ru": "Твиттер"}', 'url' => '{"en": "https://twitter.com", "hy": "https://twitter.com", "ru": "https://twitter.com"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            // ['id' => 32, 'menu_id' => 3, 'page_id' => null, 'parent_id' => null, 'image_id' => null, 'position' => 4, 'target' => '_blank', 'class' => 'btn-instagram', 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Instagram", "hy": "Ինստագրամ", "ru": "Инстаграм"}', 'url' => '{"en": "https://www.instagram.com", "hy": "https://www.instagram.com", "ru": "https://www.instagram.com"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            // ['id' => 33, 'menu_id' => 3, 'page_id' => null, 'parent_id' => null, 'image_id' => null, 'position' => 5, 'target' => '_blank', 'class' => 'btn-youtube', 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "YouTube", "hy": "Յություբ", "ru": "Ютуб"}', 'url' => '{"en": "https://www.youtube.com", "hy": "https://www.youtube.com", "ru": "https://www.youtube.com"}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            // ['id' => 34, 'menu_id' => 4, 'page_id' => 3, 'parent_id' => null, 'image_id' => null, 'position' => 0, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Terms and conditions", "hy": "Պայմաններ", "ru": "Условия"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            // ['id' => 35, 'menu_id' => 4, 'page_id' => 4, 'parent_id' => null, 'image_id' => null, 'position' => 0, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Privacy policy", "hy": "Անվտանգություն", "ru": "Приватность"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            // ['id' => 36, 'menu_id' => 4, 'page_id' => 5, 'parent_id' => null, 'image_id' => null, 'position' => 0, 'target' => null, 'class' => null, 'status' => '{"en": 1, "hy": 1, "ru": 1}', 'description' => '{"en": null, "hy": null, "ru": null}', 'title' => '{"en": "Legal notice", "hy": "Իրավական", "ru": "Юридическая информация"}', 'url' => '{"en": null, "hy": null, "ru": null}', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            
        ];

        DB::table('menus')->insert($menus);
        DB::table('menulinks')->insert($menulinks);
    }
}
